imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@DWAPSCoreBundle/Resources/config/services.yml" }
    - { resource: "@DWAPSMailsBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        dwaps: "%dwaps%"
    # form:
    #     resources: ['bootstrap_3_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

# FOSUserBundle
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: DWAPS\CoreBundle\Entity\DwapsUser

# Mobile Detect
# mobile_detect:
#     redirect:
#         full:
#             is_enabled: true            # default false
#             host: http://site.com       # with scheme (http|https), default null, url validate
#             status_code: 301            # default 302
#             action: redirect            # redirect, no_redirect, redirect_without_path
#         mobile:
#             is_enabled: true            # default false
#             host: http://m.site.com     # with scheme (http|https), default null, url validate
#             status_code: 301            # default 302
#             action: redirect            # redirect, no_redirect, redirect_without_path
#         tablet:
#             is_enabled: true            # default false
#             host: http://t.site.com     # with scheme (http|https), default null, url validate
#             status_code: 301            # default 302
#             action: redirect            # redirect, no_redirect, redirect_without_path
#         detect_tablet_as_mobile: true   # default false
#     switch_device_view:
#         save_referer_path: false        # default true
#                                         # true  redirectUrl = http://site.com/current/path?currentQuery=string
#                                         # false redirectUrl = http://site.com
#     service:
#         mobile_detector: mobile_detect.mobile_detector.default
#     cookie_key: "device_view"                     # default
#     cookie_expire_datetime_modifier: "+1 month"   # default
#     switch_param: "device_view"                   # default
#     device_view_class: "SunCat\MobileDetectBundle\Helper\DeviceView"
#     request_response_listener_class: "SunCat\MobileDetectBundle\EventListener\RequestResponseListener"
#     twig_extension_class: "SunCat\MobileDetectBundle\Twig\Extension\MobileDetectExtension"