dwaps_admin:
    resource: "@DWAPSAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

dwaps_core:
    resource: "@DWAPSCoreBundle/Resources/config/routing.yml"
    prefix:   /
    
dwaps_mails:
    resource: "@DWAPSMailsBundle/Resources/config/routing.yml"
    prefix:   /mail

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
