<?php

namespace DWAPS\CoreBundle\Repository;

/**
 * DwapsCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DwapsCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
