# Exemple route optionnelle mobile detect
# someaction:
#     pattern:  /someaction
#     defaults: { _controller: YourBundle:Index:someAction }
#     options:  { mobile: redirect, tablet: no_redirect, full: redirect_without_path } # redirect, no_redirect, redirect_without_path


# FRONT OFFICE

dwaps_core_home:
    path:     /{first_start}
    defaults:
      _controller: DWAPSCoreBundle:Main:index
      first_start: 1
    requirements:
      first_start: accueil

dwaps_core_tuto:
  path: /tuto/{id}
  defaults:
    _controller: DWAPSCoreBundle:Main:tuto
    id: 0
  requirements:
    id: \d+

dwaps_core_formations:
  path: /formations
  defaults:
    _controller: DWAPSCoreBundle:Main:formations

dwaps_core_portfolio:
  path: /portfolio
  defaults:
    _controller: DWAPSCoreBundle:Main:portfolio

dwaps_core_contact:
  path: /contact
  defaults:
    _controller: DWAPSCoreBundle:Main:contact




# BACK OFFICE

dwaps_core_nav:
    path:     /admin-nav
    defaults: 
      _controller: DWAPSCoreBundle:Admin:nav



# TEST

dwaps_core_test:
  path: /test
  defaults:
    _controller: DWAPSCoreBundle:Main:test

