# Exemple route optionnelle mobile detect
# someaction:
#     pattern:  /someaction
#     defaults: { _controller: YourBundle:Index:someAction }
#     options:  { mobile: redirect, tablet: no_redirect, full: redirect_without_path } # redirect, no_redirect, redirect_without_path

dwaps_core_home:
    path:     /{first_start}
    defaults:
      _controller: DWAPSCoreBundle:Main:index
      first_start: 1
    requirements:
      first_start: accueil

dwaps_core_tutorials:
    path: /tutorials
    defaults:
      _controller: DWAPSCoreBundle:Tuto:tutorials

dwaps_core_tutorial:
    path: /tutorial/{slug}
    defaults:
      _controller: DWAPSCoreBundle:Tuto:tutorial
    requirements:
      slug: .*
      # slug: (\w{1,30}-?){1,15}

dwaps_core_formations:
    path: /formations
    defaults:
      _controller: DWAPSCoreBundle:Main:formations

dwaps_core_portfolio:
    path: /portfolio
    defaults:
      _controller: DWAPSCoreBundle:Main:portfolio

dwaps_core_contact:
    path: /contact
    defaults:
      _controller: DWAPSCoreBundle:Main:contact