parameters:
    # app.file.twig.extension.class: DWAPS\CoreBundle\Twig\Extension\FileExtension

services:
    # app.file.twig.extension:
    #     class: %app.file.twig.extension.class%
    #     tags:
    #         - { name: twig.extension }