<?php

namespace DWAPS\ModelBundle\Repository;

/**
 * DwapsNavRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DwapsNavRepository extends \Doctrine\ORM\EntityRepository
{
}
