<?php

namespace DWAPS\ModelBundle\Repository;

/**
 * DwapsTutoContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DwapsTutoContentRepository extends \Doctrine\ORM\EntityRepository
{
}
