<?php

namespace DWAPS\ModelBundle\Repository;

/**
 * DwapsImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DwapsImageRepository extends \Doctrine\ORM\EntityRepository
{
}
