<?php

namespace DWAPS\ModelBundle\Repository;

/**
 * DwapsNavChildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DwapsNavChildRepository extends \Doctrine\ORM\EntityRepository
{
}
